services:
  - type: web
    name: tracker
    env: node
    region: frankfurt
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18.0.0